frr version 8.4_git
frr defaults traditional
hostname 9476477caeb1
no ipv6 forwarding
!
ip route 192.168.50.0/24 Null0
!
interface lo
 ip address 10.10.10.1/32
exit
!
interface eth0
 ip ospf network point-to-point
exit
!
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 172.17.0.3 remote-as 65002
 !
 address-family ipv4 unicast
  redistribute static
  redistribute ospf route-map OSPF-TO-BGP
  neighbor 172.17.0.3 soft-reconfiguration inbound
  neighbor 172.17.0.3 route-map FROM-ROUTER2 in
  neighbor 172.17.0.3 route-map ALLOW-ALL out
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.1
 redistribute static
 network 10.10.10.1/32 area 0
 network 172.17.0.0/16 area 0
exit
!
route-map ALLOW-ALL permit 10
exit
!
route-map OSPF-TO-BGP permit 10
 set metric 50
exit
!
route-map FROM-ROUTER2 permit 10
 set local-preference 200
exit
!
